@startuml reviwe-app
 skinparam linetype ortho
 hide circle

entity "users" {
  * id : bigint <<PK>>
  --
  * provider : string
  * uid : string
  * name : varchar(32)
  nickname : varchar(16)
  image : varchar(255)
  is_admin : boolean
  username_created_at : datetime
  username_updated_at : datetime
}

entity profiles {
  * id : bigint <<PK>>
  --
  * user_id  : bigint <<FK>>
  bio        : varchar(140)
  youtube    : varchar(32)
  twitch     : varchar(32)
  twitter    : varchar(32)
}

entity products {
  * id : bigint <<PK>>
  --
  * name        : varchar(256)
  * slug        : varchar(128)
  * code        : varchar(128)
  catchcopy     : varchar(256)
  manufacturer  : varchar(64)
  price         : int
  image         : varchar(256)
  review_average: float
  review_count  : smallint
  item_url      : varchar(256)
}

entity shops {
  * id : bigint <<PK>>
  --
  * name  : varchar(128)
  * code  : varchar(128)
  * url   : varchar(256)
}

entity products_shops {
  * id : bigint <<PK>>
  --
  * product_id   : bigint <<FK>>
  * shop_id  : bigint <<FK>>
}


entity reviews {
  * id : bigint <<PK>>
  --
  * user_id    : bigint <<FK>>
  * product_id  : bigint <<FK>>
  description  : varchar(1000)
  rating       : smallint
  bought_date  : datetime
}

entity analysis {
  * id : bigint <<PK>>
  --
  * product_id : bigint <<FK>>
  summary     : varchar(500)
  sentiment   : smallint
  features    : varchar(256)
}

entity tags {
  * id : bigint <<PK>>
  --
  * name : varchar(64)
}

entity products_tags {
  * id : bigint <<PK>>
  --
  * product_id   : bigint <<FK>>
  * tag_id  : bigint <<FK>>
}


users ||--|| profiles
users ||--o{ reviews
products ||--o{ reviews
products ||--|{ products_shops
shops ||--|{ products_shops
products ||--o| analysis
products ||--o{ products_tags
tags ||--o{ products_tags

@enduml