services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - type: volume
        source: psql_data
        target: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    stop_grace_period: "3s"
    restart: always

  back:
    build:
      context: ./back
      dockerfile: Dockerfile.prod
    volumes:
      - type: volume
        source: gem_data
        target: /usr/local/bundle
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 'true'
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    stdin_open: true
    tty: true
    stop_grace_period: "3s"
    restart: always

  front:
    build:
      context: ./front
      dockerfile: Dockerfile.prod
    ports:
      - '3001:3001'
    depends_on:
      - back
    environment:
      BASE_URL: ${BASE_URL_PROD}
      RAILS_API_URL: ${RAILS_API_URL}
    stdin_open: true
    tty: true
    stop_grace_period: "3s"
    restart: always

  sidekiq:
    build:
      context: ./back
      dockerfile: Dockerfile.prod
    command: bundle exec sidekiq
    volumes:
      - type: volume
        source: gem_data
        target: /usr/local/bundle
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://redis:6379/0
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAKUTEN_ID: ${RAKUTEN_ID}
      RAKUTEN_AFFILIATE: ${RAKUTEN_AFFILIATE}
    stop_grace_period: "3s"
    restart: always

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - type: volume
        source: redis_data
        target: /data
    stop_grace_period: "3s"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./certs
        target: /etc/nginx/certs
    depends_on:
      - front
      - back
    stop_grace_period: "3s"
    restart: always

volumes:
  psql_data:
  gem_data:
  redis_data:
