services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./back:/rails
      - gem_data:/usr/local/bundle
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    user: '${UID_GID}'

  front:
    working_dir: /front
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    command: pnpm run dev
    volumes:
      - type: bind
        source: ./front
        target: /front
      - type: volume
        source: node_modules
        target: /front/node_modules
    ports:
      - '3001:3001'
    depends_on:
      - back
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL_DEV}
      RAILS_API_URL: ${RAILS_API_URL}
    user: '${UID_GID}'

  sidekiq:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq
    volumes:
      - ./back:/rails
    depends_on:
      - redis
      - back
      - db
    environment:
      REDIS_URL: redis://redis:6379/0
      RAKUTEN_ID: ${RAKUTEN_ID}
      RAKUTEN_AFFILIATE: ${RAKUTEN_AFFILIATE}
    env_file:
      - .env

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - front
      - back

volumes:
  db_data:
  gem_data:
  node_modules:
