services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_DEV}
    volumes:
      - type: volume
        source: db_data_dev
        target: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    stop_grace_period: "3s"
    restart: always

  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./back
        target: /app
      - type: volume
        source: gem_data_dev
        target: /usr/local/bundle
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    stdin_open: true
    tty: true
    stop_grace_period: "3s"
    restart: always

  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./front
        target: /app
      - type: bind
        source: ./front/node_modules
        target: /app/node_modules
    ports:
      - '3001:3001'
    depends_on:
      - back
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL_DEV}
      RAILS_API_URL: ${RAILS_API_URL}
    stdin_open: true
    tty: true
    stop_grace_period: "3s"
    restart: always

  sidekiq:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq
    volumes:
      - type: bind
        source: ./back
        target: /app
      - type: volume
        source: gem_data_dev
        target: /usr/local/bundle
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      RAKUTEN_ID: ${RAKUTEN_ID}
      RAKUTEN_AFFILIATE: ${RAKUTEN_AFFILIATE}
    env_file:
      - .env
    stop_grace_period: "3s"
    restart: always

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - type: volume
        source: redis_data_dev
        target: /data
    stop_grace_period: "3s"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - type: bind
        source: ./nginx.dev.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./certs
        target: /etc/nginx/certs
    depends_on:
      - front
      - back
    stop_grace_period: "3s"
    restart: always

volumes:
  db_data_dev:
  gem_data_dev:
  redis_data_dev:
