FROM ruby:3.2.3-slim-bookworm AS assets

WORKDIR /app

ARG UID=1000
ARG GID=1000

# 必要な依存関係のインストール
RUN bash -c "set -o pipefail && apt-get update \
  && apt-get install -y --no-install-recommends build-essential curl git libpq-dev \
  && rm -rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man \
  && apt-get clean \
  && groupadd -g \"${GID}\" ruby \
  && useradd --create-home --no-log-init -u \"${UID}\" -g \"${GID}\" ruby \
  && chown ruby:ruby -R /app"

USER ruby

# Gemfileとpackage.jsonのインストール
COPY --chown=ruby:ruby Gemfile* ./
RUN bundle install

# 開発環境用の変数設定
ARG RAILS_ENV="development"
ENV RAILS_ENV="${RAILS_ENV}" \
    PATH="${PATH}:/home/ruby/.local/bin" \
    USER="ruby"

# ソースコードのコピー
COPY --chown=ruby:ruby . .

CMD ["bash", "-c", "rm -f tmp/pids/server.pid && ./bin/rails server -b '0.0.0.0'"]