# Use the official Node.js image.
FROM node:18-alpine

# Set the working directory.
WORKDIR /front

# Copy the package.json and pnpm-lock.yaml files.
COPY package.json pnpm-lock.yaml ./

# Install pnpm.
RUN npm install -g pnpm

# Install dependencies.
RUN pnpm install

# Copy the rest of the application code.
COPY . .

# Set environment variable to use port 3001
ENV PORT=3001

# Expose port 3000.
EXPOSE 3001

# Start the application.
CMD ["pnpm", "run", "dev"]